# Generated by Django 5.0.6 on 2024-06-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id_tipo_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_prestamo', models.CharField(max_length=50)),
                ('tasa_interes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('monto_prestamo', models.IntegerField()),
                ('cantidad_cuotas', models.IntegerField()),
                ('monto_pagar', models.IntegerField()),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB.empleado')),
                ('id_tipo_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB.tipoprestamo')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('numero_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('monto_cuota', models.IntegerField()),
                ('cuota_fecha_emision', models.DateTimeField()),
                ('cuota_fecha_vencimiento', models.DateTimeField()),
                ('cuota_fecha_pago', models.DateTimeField()),
                ('id_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB.prestamo')),
            ],
        ),
    ]
