# Generated by Django 5.0.6 on 2024-06-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='cuota_fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
