# Generated by Django 5.0.6 on 2024-06-29 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0002_alter_cuota_cuota_fecha_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='id_tipo_prestamo',
            new_name='tipo_prestamo',
        ),
    ]
